### ISSUE TITLE
Ghost speaker/mic

### ISSUE THREAD

**Issue by rtgxjzgsryksryydtyrkry** [henkelmax/wiretap#1] opened 2023-08-08 17:01 UTC
If the speaker or microphone unit is broken with TNT, they continue to work and cannot be removed

1. Place microphone and speaker with large distance between them
2. Unload chunks
3. load them again
4. Destroy mic or speaker in creative or with TNT
5. See error

Speaker or microphone stopped existing

no logs

**Versions**
- 1.20.1
- Fabric loader version 0.14.21
- Mod version 
- Publication date
July 23, 2023 at 12:52 PM

Fabric 
Fabric Api
Cloth config api
Simple voice chat

**Comment by henkelmax** [comment] 2023-08-08 18:04
> 1. Place microphone and speaker with large distance between them
> 2. Unload chunks
> 3. load them again
> 4. Destroy mic or speaker in creative or with TNT
> 5. See error

I can't reproduce this issue. Did you test this in singleplayer or on a server with more than one player?
I don't get any error when following these steps.

**Comment by rtgxjzgsryksryydtyrkry** [comment] 2023-08-08 18:05
Multiplayer
1 listening, 1 speaking

**Comment by rtgxjzgsryksryydtyrkry** [comment] 2023-08-08 18:12
When I broke a block in survival, it completely disappeared and there was no bug, but if it was a creative or a TNT explosion, the block broke, but did not stop working, we tested the functionality and, of course, tried to set 2 speakers of the same ID, but one of them turned off and we didn’t seem to repeat it with the subsequent ones, but the bug was repeated with new pairs

**Comment by rtgxjzgsryksryydtyrkry** [comment] 2023-08-08 18:44
Also I tried doing this agan, when I destroyed this blocks with TNT, server crashed
![image](https://github.com/henkelmax/wiretap/assets/79521533/c38fd20b-faa0-4457-88f7-05558d08f80b)

**Comment by henkelmax** [comment] 2023-08-08 18:48
> Also I tried doing this agan, when I destroyed this blocks with TNT, server crashed ![image](https://user-images.githubusercontent.com/79521533/259198245-c38fd20b-faa0-4457-88f7-05558d08f80b.png)

This was fixed in 4204618770f0ed91457b8ce3a8d87d0d342d8a10

**Comment by rtgxjzgsryksryydtyrkry** [comment] 2023-08-08 19:40
How to apply this fix?
Sorry, I'm downloading mods from modrinth

**Comment by henkelmax** [comment] 2023-08-08 19:46
Its not yet released

**Comment by henkelmax** [comment] 2023-08-08 19:48
> Also I tried doing this agan, when I destroyed this blocks with TNT, server crashed ![image](https://user-images.githubusercontent.com/79521533/259198245-c38fd20b-faa0-4457-88f7-05558d08f80b.png)

But can you send me the full error you got as text?
The current fix is kinda hacky and your error might have more information.

**Comment by rtgxjzgsryksryydtyrkry** [comment] 2023-08-08 20:01
Also I recreated bug
![image](https://github.com/henkelmax/wiretap/assets/79521533/b19af5bf-0657-42f6-bec7-708822660497)

**Comment by rtgxjzgsryksryydtyrkry** [comment] 2023-08-08 20:01
These all are different ID's

**Comment by rtgxjzgsryksryydtyrkry** [comment] 2023-08-08 21:13
I took 64 skulk, put it on the anvil, the inventory was filled with different ID microphones and speakers, placed the microphones at 200 1400, and the speakers at 0 0, then invited a friend to stand by the speakers, I teleported to the microphones, spoke, and at that time he broke one from speakers, however it continued to work

**Comment by rtgxjzgsryksryydtyrkry** [comment] 2023-08-08 21:35
> > Also I tried doing this agan, when I destroyed this blocks with TNT, server crashed ![image](https://user-images.githubusercontent.com/79521533/259198245-c38fd20b-faa0-4457-88f7-05558d08f80b.png)
> 
> But can you send me the full error you got as text? The current fix is kinda hacky and your error might have more information.
[Mods.txt](https://github.com/henkelmax/wiretap/files/12296229/Mods.txt)
[NoMods.txt](https://github.com/henkelmax/wiretap/files/12296230/NoMods.txt)

**Comment by rtgxjzgsryksryydtyrkry** [comment] 2023-08-08 22:19
Oh, also, I think you should wait until one of speakers say: Mic in unloaded chunk (or something like this)

**Comment by henkelmax** [comment] 2023-08-09 07:26
> > [Mods.txt](https://github.com/henkelmax/wiretap/files/12296229/Mods.txt)
> > [NoMods.txt](https://github.com/henkelmax/wiretap/files/12296230/NoMods.txt)

These logs don't seem to include the text you screenshotted.

**Comment by rtgxjzgsryksryydtyrkry** [comment] 2023-08-10 12:45
Sorry, I fought with Linux, I'm gonna send you a video of me and my friend recreating this bug(video is from both perspectives), It bugged every time we did that

**Comment by rtgxjzgsryksryydtyrkry** [comment] 2023-08-10 12:45
Also loggs

**Comment by henkelmax** [comment] 2023-08-10 13:28
> Also loggs

I don't need the logs anymore, but thanks! I properly fixed the Crashing issue.

**Comment by rtgxjzgsryksryydtyrkry** [comment] 2023-08-10 14:21
https://www.youtube.com/watch?v=hrhjyE6cM6I

**Comment by rtgxjzgsryksryydtyrkry** [comment] 2023-08-10 14:22
[12312.log](https://github.com/henkelmax/wiretap/files/12313889/12312.log)

**Comment by henkelmax** [comment] 2023-08-10 14:38
I did it exactly like you did in your video (with one speaker and microphone) and it worked fine for me.
Maybe its an incompatibility with another mod?
Can you try if this happens without any other mods than voice chat and this mod?

**Comment by rtgxjzgsryksryydtyrkry** [comment] 2023-08-10 17:00
This bug is still occuring even on empty server

**Comment by henkelmax** [comment] 2023-08-10 17:06
That's weird. I am not able to reproduce it.

**Comment by rtgxjzgsryksryydtyrkry** [comment] 2023-08-10 17:10
I think I know where the problem is, wee can meet in discord or I'll sed you another test

**Comment by rtgxjzgsryksryydtyrkry** [comment] 2023-08-10 17:11
chelokek1 - discord

**Closed as completed** 2023-08-10 18:58 UTC
Labels: triage
